# ---------------------------------------------------------
# TERRAFORM OUTPUTS
# ---------------------------------------------------------
# These values will be printed to your console after you run `terraform apply`.

# Prints the raw, direct URL to your API Gateway. 
# You might use this for testing your backend directly before connecting the frontend.
output "api_gateway_url" {
  description = "URL of the API Gateway"
  value       = aws_apigatewayv2_api.main.api_endpoint
}

# Prints the secure "https://" URL generated by CloudFront.
# If you aren't using a custom domain, this is the main link you will use to visit your website.
output "cloudfront_url" {
  description = "URL of the CloudFront distribution"
  value       = "https://${aws_cloudfront_distribution.main.domain_name}"
}

# Prints the exact, generated name of the S3 bucket holding your website files.
# This is helpful to know when you are ready to upload your HTML/CSS files via the AWS CLI.
output "s3_frontend_bucket" {
  description = "Name of the S3 bucket for frontend"
  value       = aws_s3_bucket.frontend.id
}

# Prints the exact name of the S3 bucket where your application stores its private memory/data.
output "s3_memory_bucket" {
  description = "Name of the S3 bucket for memory storage"
  value       = aws_s3_bucket.memory.id
}

# Prints the name of your serverless backend function.
# Useful if you need to quickly search for its logs in AWS CloudWatch.
output "lambda_function_name" {
  description = "Name of the Lambda function"
  value       = aws_lambda_function.api.function_name
}

# If you chose to use a custom domain (like yourwebsite.com), this prints that neat URL.
# If you didn't use a custom domain, it just prints a blank string.
output "custom_domain_url" {
  description = "Root URL of the production site"
  value       = var.use_custom_domain ? "https://${var.root_domain}" : ""
}